language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo pip install cpp-coveralls --use-mirrors

script: ./build.sh

after_success:
  - coveralls --exclude boost --exclude tests

